<a href="https://colab.research.google.com/github/hojuly/study_RecSys/blob/master/example_tfidf_recsys_movielens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# example_tfidf_recsys_movielens

## Preprocess

In [1]:
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [8]:
import io
from google.colab import files

uploaded = files.upload()

Saving movies.csv to movies (1).csv
Saving ratings.csv to ratings (1).csv
Saving tags.csv to tags (1).csv

In [9]:
ratings_df = pd.read_csv(io.StringIO(uploaded['ratings.csv'].decode('utf-8')))
movies_df = pd.read_csv(io.StringIO(uploaded['movies.csv'].decode('utf-8')), index_col=0)
tags_df = pd.read_csv(io.StringIO(uploaded['tags.csv'].decode('utf-8')))

In [10]:
total_count = len(movies_df.index)
total_genres = list(
    set([genre for sublist in list(map(lambda x: x.split('|'), movies_df['genres'])) for genre in sublist])
)

In [11]:
print(f"전체 영화 수: {total_count}")
print(f"장르: {total_genres}")

전체 영화 수: 9742
장르: ['War', 'Action', 'Thriller', 'Sci-Fi', 'Film-Noir', 'Comedy', 'Mystery', 'Animation', 'Children', 'Fantasy', '(no genres listed)', 'Adventure', 'Crime', 'IMAX', 'Drama', 'Musical', 'Documentary', 'Horror', 'Western', 'Romance']

## GENRES 이용

In [12]:
genre_count = dict.fromkeys(total_genres)

for each_genre_list in movies_df['genres']:
    for genre in each_genre_list.split('|'):
        if genre_count[genre] == None:
            genre_count[genre] = 1
        else:
            genre_count[genre] = genre_count[genre]+1

In [13]:
genre_count

{'(no genres listed)': 34,
 'Action': 1828,
 'Adventure': 1263,
 'Animation': 611,
 'Children': 664,
 'Comedy': 3756,
 'Crime': 1199,
 'Documentary': 440,
 'Drama': 4361,
 'Fantasy': 779,
 'Film-Noir': 87,
 'Horror': 978,
 'IMAX': 158,
 'Musical': 334,
 'Mystery': 573,
 'Romance': 1596,
 'Sci-Fi': 980,
 'Thriller': 1894,
 'War': 382,
 'Western': 167}

In [14]:
for each_genre in genre_count:
    genre_count[each_genre] = np.log10(total_count/genre_count[each_genre])
  
genre_count

{'(no genres listed)': 2.457169208193496,
 'Action': 0.7266719338379385,
 'Adventure': 0.8872447746804204,
 'Animation': 1.2026069149931968,
 'Children': 1.1664800458677336,
 'Comedy': 0.41392254164167785,
 'Crime': 0.9098289421369025,
 'Documentary': 1.3451954487495636,
 'Drama': 0.3490620385623247,
 'Fantasy': 1.0971106675631868,
 'Film-Noir': 2.0491288726171324,
 'Horror': 0.9983092704481497,
 'IMAX': 1.7899910382813284,
 'Musical': 1.4649016584241867,
 'Mystery': 1.2304935032683613,
 'Romance': 0.7856152382210405,
 'Sci-Fi': 0.9974220495432562,
 'Thriller': 0.7112681505684965,
 'War': 1.4065847623240424,
 'Western': 1.7659316540881678}

In [15]:
# create genre representations
genre_representation = pd.DataFrame(columns=sorted(total_genres), index=movies_df.index)
for index, each_row in tqdm(movies_df.iterrows()):
    dict_temp = {i: genre_count[i] for i in each_row['genres'].split('|')}
    row_to_add = pd.DataFrame(dict_temp, index=[index])
    genre_representation.update(row_to_add)

genre_representation.head()

9742it [01:05, 149.16it/s]

        (no genres listed) Action Adventure  ... Thriller  War Western
movieId                                      ...
1                      NaN    NaN  0.887245  ...      NaN  NaN     NaN
2                      NaN    NaN  0.887245  ...      NaN  NaN     NaN
3                      NaN    NaN       NaN  ...      NaN  NaN     NaN
4                      NaN    NaN       NaN  ...      NaN  NaN     NaN
5                      NaN    NaN       NaN  ...      NaN  NaN     NaN

[5 rows x 20 columns]

## TAGS 이용

In [16]:
tags_df.head(5)

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [17]:
movies_df.loc[89774]

title     Warrior (2011)
genres             Drama
Name: 89774, dtype: object

In [18]:
# get unique tag
tag_column = list(map(lambda x: x.split(','), tags_df['tag']))
unique_tags = list(set(list(map(lambda x: x.strip(), list([tag for sublist in tag_column for tag in sublist])))))

print(unique_tags)

['Crude humor', 'cartoon', 'mindless one liners', 'violence', 'Leonardo DiCaprio', 'irreverent', 'adult humor', 'Insurance', 'pregnancy', 'General Motors', 'the catholic church is the most corrupt organization in history', 'prequel', 'ironic', 'will ferrell', 'imdb top 250', 'Strangers on a Train', 'heroic bloodshed', 'cult', 'bad', 'cynical', 'Venice', 'animal movie', 'autism', 'entirely dialogue', 'Trey Parker', '2001-like', 'Aardman', 'Ghost', 'lawyers', 'not linear', 'Ben Kingsley', 'Chris Evans', 'Teen movie', 'Louisa May Alcott', 'Henry James', 'bromantic', 'Oscar (Best Supporting Actress)', 'GIVE ME BACK MY SON!', 'allegorical', 'Keanu Reeves', 'economics', 'Shakespeare', 'EPIC', 'NASA', 'dreamy', 'stop using useless characters for filler', 'ark of the covenant', 'nostalgia', 'court', 'doctors', 'Vietnam', 'Hepburn and Tracy', 'Lloyd Dobbler', 'Jude Law', 'a clever chef rat', 'lyrical', 'plastic surgery', 'Jessica Alba', 'organized crime', 'hip hop', 'meditative', 'non-linear', 'violent', 'solitude', 'anime', 'Stephen Crane', 'chess', 'monologue', 'rich guy - poor girl', 'Christmas', 'Amtrak', 'Heroic Bloodshed', 'procedural', 'chilly', 'fish', 'class', 'Adrien Brody', 'aviation', 'bad dialogue', 'fast-paced', 'mental illness', 'twisted', 'police', 'Mozart', 'In Netflix queue', 'beautiful', '"artsy"', 'organised crime', 'hallucinatory', 'divorce', 'Robert Ludlum', 'earnest', 'Housekeeper', 'Stock Market', 'Saturday Night Live', 'war', 'homeless', 'submarine', 'evil children', 'bombs', 'casual violence', 'orphans', 'romance', 'Everything you want is here', 'Andy Samberg', 'scenic', 'Jason Biggs', 'heartbreaking', 'magic board game', 'Jason', 'weather forecaster', 'updated classics', 'new society', 'great cinematography', 'Ghosts', 'colourful', 'beat poetry', 'unconventional', 'r:graphic sexuality', 'marijuana', 'American Indians', 'race', 'murder', 'stapler', 'Alicia Vikander', 'Jared Leto', 'British gangster', 'trains', 'non-linear timeline', 'double life', 'heroine in tight suit', 'remix culture', 'killer-as-protagonist', 'nocturnal', 'Up series', 'DC Comics', 'poor dialogue', 'fairy tale', 'mind-bending', 'KIDNAPPING', 'Kevin Spacey', 'Samuel L. Jackson', 'stylish', 'Michael Crichton', 'Adventure', 'planes', 'alone in the world', 'grim', 'pageant', 'figure skating', 'gritty', 'pizza beer', 'Mexico', 'joss whedon', 'paranoia', 'bizarre', 'tear jerker', 'great acting', 'tobacco', 'cheesy', 'stiller', 'Cambodia', 'quirky romantic', 'spiders', 'postmodern', 'good music', 'multiple short stories', 'John Travolta', 'Borg', 'Juliette Lewis', 'britpop', 'Rachel Weisz', 'innovative', 'societal criticism', 'Great performances', 'claustrophobic', 'teenagers', 'Hilary Swank', 'futuristic', 'Turkey', 'true story', 'Mental Hospital', 'fighting', 'thriller', 'circus', 'James Franco', 'brainwashing', 'apes', 'Gulf War', 'Hungary', 'Capone', 'video games', 'geeky', 'biking', 'fast paced', 'fun family movie', 'leonardo DiCarpio', 'small time criminals', 'McCarthy hearings', 'black hole', 'French', 'Anne Hathaway', 'future', 'visually stunning', 'creativity', 'witty', 'alcoholism', 'cool', 'books', 'slow action', 'realistic', 'cheeky', 'Kevin Smith', 'boxing', 'bible', 'political commentary', 'spoof', 'r:strong bloody violence', 'satirical', 'pixar', 'David Thewlis', 'Mystery', 'stephen king', 'dc comics', 'spies', '1900s', 'fatherhood', 'tricky', 'meryl streep', 'aardman', 'Post apocalyptic', 'Politics', 'Cold', 'big name actors', 'visual', 'beautiful visuals', 'George Clooney', 'father-son relationship', 'Edith Wharton', 'episodic', 'Toto', 'alan rickman', 'movie business', 'longing', 'vertriloquism', 'surfing', 'Las Vegas', 'a dingo ate my baby', 'magic', 'good', 'families', 'gold', 'Wall Street', 'falling', 'video game adaptation', 'Brittany Murphy', 'offensive', 'stylized', 'opera', 'Will Smith', 'ben stiller', 'dinosaurs', 'Soundtrack', 'Train', 'aggressive', 'cruel characters', 'martial arts', 'big budget', 'really bad', 'Tarantino', 'bad writing', 'parrots', 'teen', 'Audrey Tautou', 'Guns', 'costume drama', 'baseball', 'goofy', 'British', 'visually appealing', 'animation', 'Hammett', 'Klingons', 'factory', 'India', 'great performances', 'remade', 'scifi', 'lesbian subtext', 'Tradition!', 'trippy', 'AWESOME', 'sofia coppola', 'infertility', 'lack of development', "Harley Quinn's ass", 'seen more than once', 'predictible plot', 'space action', 'anti-Semitism', 'teacher', 'soccer', 'time travel', 'rabbi', 'setting:space/space ship', 'Afghanistan', 'Tom Clancy', 'space epic', 'vampire', 'werewolf', 'Broadway', 'funny', 'Lolita theme', 'Chuck Palahniuk', 'Sci-Fi', 'Stoner Movie', 'Pixar', 'Simon and Garfunkel', 'Maggie Gyllenhaal', 'purposefulness', 'the Force', 'Steven Spielberg', 'MCU', 'narnia', 'Colin Farrell', 'existentialism', 'large cast', 'cancer', 'space adventure', 'brutal', 'biblical references', 'great screenplay', 'Poor story', 'mobster', 'McDonalds', 'singletons', 'reciprocal spectator', 'diabetes', 'great dialogue', 'lions', 'white guilt', 'Middle East', 'intellectual', 'Ralph Fiennes', 'Seth MacFarlane', 'Guardians of the Galaxy', 'China', 'leopard', 'Narrative pisstake', 'whales', 'Comedy', 'Dinosaur', 'made me cry', 'Gary Oldman', 'Big Brothers', 'Matrix', 'nonlinear timeline', 'SPACE TRAVEL', 'I see dead people', 'shark', 'scandal', 'high school', 'computer animation', 'Dumas', 'AS Byatt', 'roald dahl', 'Anne Boleyn', 'L.A.', 'prostitution', 'free to download', 'England', 'e-mail', 'mountain climbing', 'splatter', 'Andy Kaufman', 'sophisticated', 'action', 'POW', 'weak plot', 'cyberpunk', 'Paul Rudd', 'Psychological Thriller', 'nuclear war', 'not funny', 'Siam', 'justice', 'Harper Lee', 'singers', 'Hal', 'Francis Ford Coppola', 'jungle', 'Savannah', 'Arthur Miller', 'great ending', 'road trip', 'espionage', 'mad scientist', 'male nudity', 'kung fu', 'Dialogue', 'Stones of Summer', 'pigs', 'mystery', 'cult classic', 'Michigan', 'South America', 'Johnny Cash', 'Tom Hanks', 'gun fu', 'beautiful scenery', 'stupid but funny', 'domestic violence', 'Graham Greene', 'anthology', 'Robin Williams', 'Jake Gyllenhaal', 'unlikely hero', 'original plot', 'humorous', 'needed more autobots', 'They Might Be Giants', 'sarcasm', 'ballet', 'androids', 'epic', 'deafness', 'President', 'lesbian', 'rasicm', 'fairy tales', 'radio', 'claims to be true', 'Magneto', 'unpredictable', 'film noir', 'bubba gump shrimp', 'convent', 'twist', 'Dan Aykroyd', 'tragedy', 'robbery', 'prom', 'post-apocalyptic', 'theater', 'FBI', 'graphic design', 'mel gibson', 'inhumane', 'dark comedy', 'computers', 'hope', 'interesting', 'pulp', 'jim carrey', 'cross dressing', 'intimate', 'Navy', 'terminal illness', 'freedom of expression', 'biography', 'dance', 'dancing', 'social commentary', 'retro', 'Jean Grey', 'uncomfortable', 'bad-ass', 'men in drag', 'new composer', 'teachers', 'tension building', 'generation X', 'Chile', 'Palahnuik', 'seen at the cinema', 'conversation', 'remake', 'fantasy', 'workplace', 'Screwball', 'Exquisite plotting.', 'suicide', 'freaks', 'surprise ending', 'Great movie', 'Captain Kirk', 'Jim Morrison', 'bruce willis', 'Doc Ock', 'enjoyable', 'Sci-fi', 'Charles Dickens', 'ROBOTS AND ANDROIDS', 'It was melodramatic and kind of dumb', 'crucifixion', 'Not available from Netflix', 'loneliness', 'faerie tale', 'music', 'Titanic', 'good soundtrack', 'revenge', 'new york', 'Beatles', 'multiple personalities', 'sisterhood', 'subway', 'oninous', 'Olympics', 'James Fennimore Cooper', 'Sundance award winner', 'philosophical', 'crime scene scrubbing', 'Harley Quinn', 'british comedy', 'knights', 'enigmatic', 'asylum', 'dumb', 'Romans', 'evolution', 'narrated', '2D animation', 'ensemble cast', 'eerie', 'immortality', 'nonlinear narrative', 'Steve Carell', 'Black comedy', '1950s', 'Alcatraz', 'classic movie', 'Star Trek', 'violence in america', 'Istanbul', 'not seen', 'terrorism', 'spying', 'menacing', 'history', 'PTSD', 'claymation', 'last man on earth', 'shrimp', 'surrealism', 'HORRIBLE ACTING', 'dogs', 'star wars', 'zombies', 'Missionary', 'nonlinear', 'sexy', 'space', 'no dialogue', 'Nathan Fillion', 'stupid is as stupid does', 'Russell Crowe', 'truth', 'samurai', 'Sexual Humor', 'John Malkovich', 'indie record label', 'school', 'touching', 'ben affleck', 'controversial', 'Dr. Seuss', 'Oscar (Best Effects - Visual Effects)', 'memory', 'Dark', 'artsy', 'Bad writing', 'stand-up comedy', 'Othello', 'old', 'Stephen King', 'amnesia', 'moldy', 'Star Wars', 'coma', 'David Bowie', 'Nuclear disaster', 'Depressing', 'Rosebud', 'camp', 'classic', 'child abuse', 'Judaism', 'assassination', 'science fiction', 'passion', 'Thrilling', 'Rita Hayworth can dance!', 'Batman', 'Arnold Schwarzenegger', 'avant-garde romantic comedy', 'Capote', 'Macaulay Culkin', 'multiple storylines', 'rebellion', 'art house', 'tolkien', 'Coen Bros', 'r:disturbing violent images', 'motherfucker', 'Renee Zellweger', 'ummarti2006', 'complicated', 'memory loss', 'Humour', 'amazing dialogues', 'sweet', 'CGI', 'amazing', 'Jim Carrey', 'Bechdel Test:Fail', 'Roger Avary', 'space travel', 'documentary', 'swashbuckler', 'Peter Pan', 'The Entertainer', 'helena bonham carter', 'artificial intelligence', 'sentimental', 'Rob Zombie', 'human rights', 'small towns', 'military', 'feel-good', 'slasher', 'humane', 'hugh jackman', 'HOT actress', 'dreamlike', 'voyeurism', 'characters', 'Nabokov', 'Casey Affleck', 'Mark Ruffalo', 'coen brothers', 'beautifully filmed', 'rug', 'Adam Sandler', 'motherhood', 'Salieri', 'Watergate', 'short films', 'western', 'twists & turns', 'gunfight', 'von Bulow', 'Rome', 'sex', 'winona ryder', 'Nick Hornby', 'good cinematography', 'weird', 'Brooch', 'Creature Feature', 'prejudice', 'DC', 'robots', 'genocide', 'alter ego', 'dark', 'dust bowl', 'freedom', 'technology', 'bleak', 'bad music', 'oil', 'diner', 'interracial marriage', 'tense', 'different', 'John Cusack', 'slow paced', 'Rogers and Hammerstein', 'revolutionary', 'Shangri-La', 'quick cuts', 'illusions', 'horror', 'action packed', 'elegiac', 'televangelist', 'George Bernard Shaw', 'James Stewart', 'Funny', 'Al Pacino', 'saints', 'nightmare', 'France', 'mice', 'Wizards', 'ridiculous', 'killer', 'unintelligent', 'atmospheric', 'very funny', 'kidnapping', 'Dystopia', 'cryptic', 'Bruce Willis', 'mobsters', 'oldie but goodie', 'heist', 'New York City', 'tom hardy', 'mental hospital', 'sad', 'celebrity fetishism', 'beautiful cinematography', 'coke', 'Notable Nudity', 'BEST PICTURE', 'action choreography', 'political right versus left', 'r:disturbing violent content including rape', 'Cold War', 'wistful', 'Holy Grail', 'happpiness', 'Clock', 'moody', 'superficial plot', 'gore', 'sports', 'noir', 'inspirational', 'harsh', 'real estate', 'Gal Gadot', 'Japan', 'women', 'emotional', 'comic book', 'Nun', 'photographer', 'cattle drive', 'adventure', 'daniel craig', 'Thor', 'ballroom dance', 'Simple', 'con men', 'Uma Thurman', 'tearjerking', 'nonsense', 'neo-noir', '1920s', 'post-college', 'cult film', 'powerful ending', 'modern fantasy', 'genius', 'anti-intellectual', 'Quotable', 'big corporations', 'representation of children', 'Poor plot development', 'Eva Green', 'challenging', 'superhero', 'Hollywood', 'travolta', 'Prince', 'fast-paced dialogue', 'big wave', 'space craft', 'best comedy', 'TOGA', 'artistic', 'romantic comedy', 'sisters', 'interesting characters', 'bears', 'tragic', 'suspenseful', 'Journalism', 'imaginative', 'children', 'overcomplicated', 'highschool', 'Paris', 'plot twist', 'gintama', 'Marvel', 'system holism', 'obsession', 'android(s)/cyborg(s)', '70mm', 'philosopical', 'random', 'Veterinarian', 'Jeff Bridges', 'Clousseau', 'psychedelic', 'china', 'bad ass', 'black comedy', 'test tag', 'Denzel Washington', 'mathematics', 'melancholy', 'Studio Ghibli', 'secrets', 'alternate reality', 'flood', 'boksdrama', 'aliens', 'Orlando Bloom', 'Viggo Mortensen', 'darth vader', 'Marx brothers', 'Jesse Eisenberg', 'meaningless violence', 'horses', 'Bill Murray', 'Angelina Jolie', 'South Africa', 'elegant', 'donkey', 'r:violence', 'Highly quotable', 'adoption', 'bad jokes', 'dumpster diving', 'Union', 'Nerd', 'Hugh Jackman', 'Butler', 'crappy sequel', 'batman', 'Kurt Russell', 'dark hero', 'twist ending', 'philosophical issues', 'Julianne Moore', 'Agatha Christie', 'Action', 'Ryan Reynolds', 'Quentin Tarantino', 'stupid', 'masterpiece', 'fantasy world', 'journalism', 'Modern war', 'Charlize Theron', 'courtroom drama', 'love story', 'nuns', 'Mount Rushmore', 'golf', 'Sustainability', 'prodigies', 'Twist Ending', 'gun-fu', 'independent', 'Death', 'aging', 'Civil War', 'bank', 'Jennifer Connelly', 'E.M. Forster', 'gangster', 'lovely', 'Mel Gibson', 'amazing artwork', 'Seth Rogen', 'saint', 'suspense', 'relaxing', 'Dodie Smith', 'reflective', 'gambling', 'Beethoven', 'alternate endings', 'depression', 'film-noir', 'Arthur C. Clarke', 'Margot Robbie', 'good writing', 'based on a TV show', 'coulda been a contender', 'poorly paced', 'satire', 'business', 'Medieval', 'good and evil', 'moon', 'Food', 'assassin', 'virtual reality', 'Lonesome Polecat', 'twins', 'Tennessee Williams', 'spaghetti western', 'Dickens', 'shipwreck', 'Music', 'Insanity', 'Amish', 'Cole Porter', 'cia', 'way too long', 'I am your father', 'comics', 'haunting', 'dialogue', 'con artists', 'Cerebral', 'drugs & music', 'sci-fi', 'Hearst', 'Mrs. DeWinter', 'sexy female scientist', 'post apocalyptic', 'salute to Douglas Sirk', 'blindness', 'dreams', 'incest', 'goretastic', 'city politics', 'creepy', 'Priest', 'thought-provoking', 'boring', 'start of a beautiful friendship', 'overrated', 'Documentary', 'aquarium', 'audience intelligence underestimated', 'transplants', 'food', 'jake gyllenhaal', 'Joker', 'too long', 'plot holes', 'Christopher Lloyd', 'kids', 'show business', 'money', 'awkward romance', 'austere', 'Bette Davis', 'TERRORISM', 'archaeology', 'far fetched', 'Josh Brolin', 'Norman Bates', 'based on a play', 'virginity', 'Philip Seymour Hoffman', 'masculinity', 'wapendrama', 'George Lucas', 'apocalypse', 'achronological', 'birds', 'Christian Bale', 'lawyer', 'ransom', 'movies', 'mockumentary', 'bus', 'cheating', 'edward norton', 'Scotland', 'steve carell', 'Harvey Keitel', 'Metaphorical', 'space opera', 'mind-blowing', 'Jean Reno', 'lies', 'directorial debut', 'football', 'silly', 'Dr. Strange', 'nonlinear storyline', 'conspiracy', 'uplifting', 'transvestite', 'Nudity (Full Frontal)', 'interesting scenario', 'pool', 'daniel radcliffe', 'sequel', 'zoe kazan', 'Morrow', 'MMA', 'understated', 'Truman Capote', 'biopic', 'imagination', 'tension', 'arthouse', 'unoriginal', 'restaurant', 'assassin-in-training (scene)', 'Quirky', 'unusual', 'hula hoop', 'Jekyll and Hyde', 'Conan', 'Amazing Cinematography', 'Suspense', 'stupid ending', 'Pearl S Buck', 'annoying', 'franchise', 'unexplained', 'drugs', 'Johnny Depp', 'Holocaust', 'Disney animated feature', 'Amy Adams', 'engrossing adventure', 'Christina Ricci', 'black-and-white', 'Atomic bomb', 'philosophy', 'inspiring', 'captain nemo', 'Hayao Miyazaki', 'Dorothy', 'religion', 'Tim Burton', 'bad humor', 'Insane', 'racism', 'crime', 'long takes', 'Shia LaBeouf', 'good dialogue', 'King Arthur', 'Australia', 'lion', 'S.E. Hinton', 'symbolic', 'rape', 'big boys with guns', 'reunion', 'guns', 'Bittersweet', 'mediacentralism', 'macho', 'computer', 'butler', 'high fantasy', 'doll', 'game', 'Jaime Pressly', 'Inigo Montoya', 'creative', 'Emilia Clarke', 'zither', 'C.S. Lewis', 'poetic', 'Police', 'Magic', 'awkward', 'Animal movie', 'death penalty', 'Boxing story', 'indiana jones', 'Backwards. memory', 'threesome', 'David Fincher', 'lieutenant dan', 'Stand Up', 'Simon Pegg', 'original', 'wedding', 'Eric Bana', 'Atmospheric', 'brutality', 'hilarious', 'wine', 'ex-con', 'accident', 'poignant', 'Hannibal Lecter', 'character study', 'FIGHTING THE SYSTEM', 'christmas', 'Scifi masterpiece', 'Slim Pickens', 'Suspenseful', 'skiing', 'six-fingered man', 'Mark Wahlberg', 'hippies', 'hit men', 'too much love interest', 'pop culture references', 'Shark', 'weddings', 'heartwarming', 'mecha', 'Morgan Freeman', 'crude humor', 'disability', 'exciting', 'corruption', 'missionary', 'Visually appealing', 'Thanos', 'lack of plot', 'love', 'remaster', 'south park', 'anger', 'happy ending', 'Horror', 'Rogue', 'adorable', 'Jack Nicholson', 'Mindfuck', 'stranded', 'imaginary friend', 'classic sci-fi', 'immigrants', 'space station', 'Ireland', 'Henry Darger', 'interwoven storylines', 'schizophrenia', 'slick', 'Gangs', 'Oscar (Best Actress)', 'gruesome', 'ancient Rome', 'blood splatters', 'mafia', 'Europe', 'Italy', 'parenthood', 'off-beat comedy', 'insanity', 'Mafia', 'royal with cheese', 'Western', 'SNL', 'May-December romance', 'storytelling', 'film history', 'Dogs', 'time-travel', 'John Goodman', 'E. M. Forster', 'Favelas', 'spelling bee', 'childish naivity', 'financial crisis', 'screwball', 'r:some violence', 'Bible', 'John Grisham', 'Will Ferrell', 'parody', 'surreal', 'absorbing', 'independent film', 'short stories', 'smart', 'fun', 'somber', 'dead wife', 'stage', 'bad language', 'Emma', 'Revenge', 'Ray Bradbury', 'royalty', 'Native Americans', 'Rachel McAdams', 'psychiatrist', 'individualism', 'Horrid characterisation', 'cliche characters', 'Tom Hardy', 'superb soundtrack', 'mythology', 'brilliant', 'awesome', 'Tilda Swinton', 'alternate universe', 'Jane Austen', 'Nazis', 'easygoing', 'mindfuck', 'insomnia', 'Hawkeye', 'Lou Gehrig', 'Wesley Snipes', 'halloween', 'vampires', 'personals ads', 'Russia', 'hostage', 'paranoid', 'cinematography', 'emma thompson', 'cate blanchett', 'jazz', 'Heartwarming', 'blood', 'preacher', 'Luc Besson', 'villain nonexistent or not needed for good story', 'Charlotte Bronte', 'babies', 'bizzare', 'Great Visuals', 'long shots', 'ending', 'scary', 'sniper', 'symbolism', 'Deep Throat', 'Jesse Ventura', 'mermaid', 'building a family', 'Moving', 'Tokyo', 'treasure hunt', 'for katie', 'spacecraft', 'island', 'abortion', 'Eccentric', 'Empire State Building', 'Classic', 'multiple roles', 'Oscar Wilde', 'Dull', 'Vulgar', 'Peta Wilson', 'Something for everyone in this one... saw it without and plan on seeing it with kids!', 'lawn mower', 'Monty Python', 'Grace', 'Moses', 'nightclub', 'entertaining', 'luke skywalker', 'Ben Affleck', 'movies about movies', 'slavery', 'Anthony Hopkins', 'dark humor', 'Philip K. Dick', 'Existential', 'golfing', 'writing', '1960s', 'Motivational', 'suburbia', 'drug abuse', 'Thanksgiving', 'self discovery', "Palme d'Or", 'bad script', 'Family', 'live action/animation', 'intense', 'bittersweet', 'intertwining storylines', 'Tolstoy', 'gun tactics', 'World War II', 'Africa', 'morality', 'irony', 'Martin Scorsese', 'Astaire and Rogers', 'family', 'comedy', 'confrontational', 'Nicolas Cage', 'Edward Norton', 'Tolkien', 'revolution', 'heavy metal', 'priest', '06 Oscar Nominated Best Movie - Animation', 'Alfred Hitchcock', 'Hemingway', 'addiction', 'Einstein', 'introspection', 'painter', 'missing children', 'Jennifer Lawrence', 'Dwayne Johnson', 'r:sustained strong stylized violence', 'Stanley Kubrick', 'death', 'hitman', 'gangs', 'widows/widowers', 'wonderwoman', 'casino', 'stop looking at me swan', 'historical', 'Animation', 'TV', 'Bad story', 'Recap', 'mining', 'deadpan', 'embarassing scenes', 'Ben Stiller', 'Jason Segel', 'deaf', 'shenanigans', 'R language', 'psychological', 'DEPRESSING', 'politics', 'Liam Neeson', 'Robert De Niro', 'unsettling', 'Unique', 'black humour', 'younger men', 'Matt Damon', 'jack nicholson', 'jay and silent bob', 'psychological thriller', 'dance marathon', 'AIDs', 'gothic', 'bromance', 'wizards', 'drama', 'Robert Downey Jr.', 'serial killer', 'Ichabod Crane', 'cool style', 'unique', 'MacBeth', 'moving', 'Woody Harrelson', 'Peace Corp', 'In Your Eyes', 'friendship', 'No DVD at Netflix', 'television', 'thought provoking', 'Hannibal Lector', 'Seann William Scott', 'purity of essence', 'rap', 'predictable', 'american idolatry', 'milkshake', 'crazy', 'nanny', "80's", 'Wel

In [19]:
print(len(tag_column))
print(len(unique_tags))

3683
1589

In [ ]:
# Compute IDF for tag
total_movie_count = len(set(tags_df['movieId']))
# key: tag, value: number of movies with such tag
tag_count_dict = dict.fromkeys(unique_tags)

for each_movie_tag_list in tags_df['tag']:
    for tag in each_movie_tag_list.split(","):
        if tag_count_dict[tag.strip()] == None:
            tag_count_dict[tag.strip()] = 1
        else:
            tag_count_dict[tag.strip()] += 1

tag_idf = dict()
for each_tag in tag_count_dict:
    tag_idf[each_tag] = np.log10(total_movie_count / tag_count_dict[each_tag])

tag_idf

In [21]:
len(tag_idf.keys())

1589

In [22]:
# Create movie representations
tag_representation = pd.DataFrame(columns=sorted(unique_tags), index=list(set(tags_df['movieId'])))
for name, group in tqdm(tags_df.groupby(by='movieId')):
    temp_list = list(map(lambda x: x.split(','), list(group['tag'])))
    temp_tag_list = list(set(list(map(lambda x: x.strip(), list([tag for sublist in temp_list for tag in sublist])))))

    dict_temp = {i: tag_idf[i.strip()] for i in temp_tag_list}
    row_to_add = pd.DataFrame(dict_temp, index=[group['movieId'].values[0]])
    tag_representation.update(row_to_add)

tag_representation = tag_representation.sort_index(0)
tag_representation.head()

100%|██████████| 1572/1572 [05:06<00:00,  5.12it/s]

  "artsy" 06 Oscar Nominated Best Movie - Animation  ... zoe kazan zombies
1     NaN                                       NaN  ...       NaN     NaN
2     NaN                                       NaN  ...       NaN     NaN
3     NaN                                       NaN  ...       NaN     NaN
5     NaN                                       NaN  ...       NaN     NaN
7     NaN                                       NaN  ...       NaN     NaN

[5 rows x 1589 columns]

In [23]:
movies_df.head()

                                      title                                       genres
movieId
1                          Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
2                            Jumanji (1995)                   Adventure|Children|Fantasy
3                   Grumpier Old Men (1995)                               Comedy|Romance
4                  Waiting to Exhale (1995)                         Comedy|Drama|Romance
5        Father of the Bride Part II (1995)                                       Comedy

In [24]:
tag_representation.loc[1].dropna()

fun      2.49748
pixar    2.89542
Name: 1, dtype: object

In [25]:
tag_representation.loc[2].dropna()

Robin Williams      2.71933
fantasy              2.4183
game                3.19645
magic board game    3.19645
Name: 2, dtype: object

In [26]:
print(genre_representation.shape)
print(tag_representation.shape)

(9742, 20)
(1572, 1589)

In [27]:
movie_representation = pd.concat([genre_representation, tag_representation], axis=1).fillna(0)
print(movie_representation.shape)
movie_representation.describe()

(9742, 1609)

       (no genres listed)       Action  ...    zoe kazan      zombies
count         9742.000000  9742.000000  ...  9742.000000  9742.000000
mean             0.008576     0.136354  ...     0.000328     0.001241
std              0.144915     0.283726  ...     0.032385     0.054775
min              0.000000     0.000000  ...     0.000000     0.000000
25%              0.000000     0.000000  ...     0.000000     0.000000
50%              0.000000     0.000000  ...     0.000000     0.000000
75%              0.000000     0.000000  ...     0.000000     0.000000
max              2.457169     0.726672  ...     3.196453     2.418301

[8 rows x 1609 columns]

## Contents 유사도 평가

In [28]:
from sklearn.metrics.pairwise import cosine_similarity


def cos_sim_matrix(a, b):
    cos_sim = cosine_similarity(a, b)
    result_df = pd.DataFrame(data=cos_sim, index=[a.index])
    return result_df

In [29]:
movie_representation.head()

   (no genres listed)  Action  Adventure  ...  zither  zoe kazan  zombies
1                 0.0     0.0   0.887245  ...     0.0        0.0      0.0
2                 0.0     0.0   0.887245  ...     0.0        0.0      0.0
3                 0.0     0.0   0.000000  ...     0.0        0.0      0.0
4                 0.0     0.0   0.000000  ...     0.0        0.0      0.0
5                 0.0     0.0   0.000000  ...     0.0        0.0      0.0

[5 rows x 1609 columns]

In [30]:
cs_df = cos_sim_matrix(movie_representation, movie_representation)
cs_df.head()

       0         1         2     ...      9739      9740      9741
1  1.000000  0.124438  0.008403  ...  0.000000  0.232553  0.093519
2  0.124438  1.000000  0.000000  ...  0.000000  0.000000  0.000000
3  0.008403  0.000000  1.000000  ...  0.000000  0.000000  0.089849
4  0.040571  0.000000  0.179391  ...  0.365843  0.000000  0.433821
5  0.011755  0.000000  0.011294  ...  0.000000  0.000000  0.125697

[5 rows x 9742 columns]

In [31]:
cs_df.shape

(9742, 9742)

In [32]:
print(cs_df.shape)
cs_df[1].sort_values(ascending=False)

(9742, 9742)

2         1.000000
46972     0.322201
126142    0.300850
2043      0.300850
2399      0.300850
            ...
39449     0.000000
39516     0.000000
39715     0.000000
39869     0.000000
7299      0.000000
Name: 1, Length: 9742, dtype: float64

In [33]:
print(movies_df.loc[1])
print(movies_df.loc[46972])
print(movies_df.loc[126142])
print(movies_df.loc[2043])
print(movies_df.loc[2399])

title                                Toy Story (1995)
genres    Adventure|Animation|Children|Comedy|Fantasy
Name: 1, dtype: object
title     Night at the Museum (2006)
genres    Action|Comedy|Fantasy|IMAX
Name: 46972, dtype: object
title     The Cave of the Golden Rose (1991)
genres            Adventure|Children|Fantasy
Name: 126142, dtype: object
title     Darby O'Gill and the Little People (1959)
genres                   Adventure|Children|Fantasy
Name: 2043, dtype: object
title     Santa Claus: The Movie (1985)
genres       Adventure|Children|Fantasy
Name: 2399, dtype: object

## 성능 평가

In [34]:
train_df, test_df = train_test_split(
    ratings_df,
    test_size=0.2,
    random_state=1234
)

In [35]:
print(train_df.shape)
print(test_df.shape)

(80668, 4)
(20168, 4)

In [ ]:
test_userids = list(set(test_df.userId.values))
test_userids

In [37]:
result_df = pd.DataFrame()

for user_id in tqdm(test_userids):
    user_record_df = train_df.loc[train_df.userId == int(user_id), :]
    
    user_sim_df = cs_df.loc[user_record_df['movieId']]  # (n, 9742); n은 userId가 평점을 매긴 영화 수
    user_rating_df = user_record_df[['rating']]  # (n, 1)
    sim_sum = np.sum(user_sim_df.T.to_numpy(), -1)  # (9742, 1)
    # print("user_id=", i, user_record_df.shape, user_sim_df.T.shape, user_rating_df.shape, sim_sum.shape)

    prediction = np.matmul(user_sim_df.T.to_numpy(), user_rating_df.to_numpy()).flatten() / (sim_sum+1) # (9742, 1)

    prediction_df = pd.DataFrame(prediction, index=cs_df.index).reset_index()
    prediction_df.columns = ['movieId', 'pred_rating']    
    prediction_df = prediction_df[['movieId', 'pred_rating']][prediction_df.movieId.isin(test_df[test_df.userId == user_id]['movieId'].values)]

    temp_df = prediction_df.merge(test_df[test_df.userId == user_id], on='movieId')
    result_df = pd.concat([result_df, temp_df], axis=0)

100%|██████████| 610/610 [00:21<00:00, 28.24it/s]

In [38]:
result_df.head(10)

   movieId  pred_rating  userId  rating  timestamp
0        1     4.145652       1     4.0  964982703
1       50     3.650755       1     5.0  964982931
2      216     2.670124       1     5.0  964981208
3      223     2.612844       1     3.0  964980985
4      231     4.215284       1     5.0  964981179
5      235     3.619820       1     4.0  964980908
6      316     4.136756       1     3.0  964982310
7      457     3.218743       1     5.0  964981909
8      543     3.729524       1     4.0  964981179
9      592     4.024728       1     4.0  964982271

In [39]:
mse = mean_squared_error(y_true=result_df['rating'].values, y_pred=result_df['pred_rating'].values)
rmse = np.sqrt(mse)

print(mse, rmse)

1.40606646706041 1.1857767357561078